name: 'Update infra'

inputs:
  WORKSPACE_NAME:
    description: 'The name of the Terraform workspace'
    required: true
  API_URL:
    description: 'The API URL'
    required: true
  WEBSITE_URL:
    description: 'The website URL'
    required: true
  ENVIRONMENT:
    description: 'The environment'
    required: true

env:
  INFRA_DIR: './packages/infra'
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
  API_URL: ${{ inputs.API_URL }}
  WEBSITE_URL: ${{ inputs.WEBSITE_URL }}
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
  WORKSPACE_NAME: ${{ inputs.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Check if input is missing
      if: ${{ env.ENVIRONMENT == '' }}
      run: |
        echo "::error::Missing required input: my_input"
        exit 1
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Workspace Select
      id: terraform-workspace-select
      shell: bash
      working-directory: ${{ env.INFRA_DIR }}
      run: terraform workspace select -or-create ${{ env.WORKSPACE_NAME }}

    - name: Terraform Init
      id: terraform-init
      run: terraform init
      shell: bash
      working-directory: ${{ env.INFRA_DIR }}

    - name: Terraform Format
      id: terraform-format
      run: terraform fmt -check
      shell: bash
      working-directory: ${{ env.INFRA_DIR }}

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -input=false
      shell: bash
      working-directory: ${{ env.INFRA_DIR }}

    - name: Terraform Apply
      id: terraform-apply
      shell: bash
      working-directory: ${{ env.INFRA_DIR }}
      run: terraform apply -auto-approve -input=false