name: 'Build frontend'
description: 'Build frontend'
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account ID'
    required: true
  BRANCH_NAME:
    description: 'Terraform workspace name'
    required: true
  DISABLE_DOMAIN_INDEXING:
    description: 'Add custom headers to disable indexing'
    required: true
    default: 'true'
  WEBSITE_URL:
    description: 'URL'
    required: true
  FRONTEND_BUILD_PATH:
    description: 'Path to frontend build'
    default: 'apps/marketing/.vercel/output/static'
    required: false

outputs:
  FRONTEND_BUILD_PATH:
    description: 'Path to frontend build'
    value: ${{ inputs.FRONTEND_BUILD_PATH }}

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build frontend
      run: npm run build-ci
      shell: bash

    - name: Add custom headers
      run: |
        echo "${{ inputs.WEBSITE_URL }}" >> ${{ inputs.FRONTEND_BUILD_PATH }}/_headers
        echo -e "\tX-Robots-Tag: noindex" >> ${{ inputs.FRONTEND_BUILD_PATH }}/_headers
      shell: bash

    - name: Upload frontend build
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy ${{ inputs.FRONTEND_BUILD_PATH }} --project-name marketing-${{ inputs.BRANCH_NAME }} --branch main