name: 'Deploy app'

inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'The Cloudflare API token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'The Cloudflare account ID'
    required: true
  API_ENV:
    description: 'The api environment to deploy to'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Build apps
      run: npm run build
      shell: bash

    - name: Deploy api
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy --env ${{ inputs.API_ENV }}
        workingDirectory: "./apps/api"

    - name: Deploy marketing
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy .vercel/output/static --project-name marketing-${{ inputs.API_ENV }}
        workingDirectory: "./apps/marketing"
