name: 'Deploy app'

permissions:
  contents: read

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Deploy api
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
        command: deploy --env production
        workingDirectory: "./packages/api"
