name: 'Deploy app'

inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'The Cloudflare API token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'The Cloudflare account ID'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Deploy api
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy --env production
        workingDirectory: "./apps/api"
