name: 'Check infra'

inputs:
  TF_API_TOKEN:
    description: 'The Terraform API token'
    required: true
  INFRA_DIR:
    description: 'The directory where Terraform configurations are located'
    required: true
    default: './packages/infra'

runs:
  using: "composite"
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      id: setup-terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}

    - name: Terraform Init
      id: terraform-init
      run: terraform init
      working-directory: ${{ inputs.INFRA_DIR }}

    - name: Terraform Format
      id: terraform-format
      run: terraform fmt -check
      working-directory: ${{ inputs.INFRA_DIR }}

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -input=false
      working-directory: ${{ inputs.INFRA_DIR }}
