// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
    SUPABASE_URL: string;
    SUPABASE_ANON_KEY: string;
}
