name: 'Check variables'

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

permissions:
  contents: read

jobs:
  check-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.ref }}"
        shell: bash