name: 'Deploy preview environment'

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - in_progress

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-infra:
    environment: preview
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
      TF_VAR_BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
      TF_VAR_API_URL: ${{ github.event.workflow_run.head_branch }}-${{ vars.API_URL }}
      TF_VAR_WEBSITE_URL: ${{ github.event.workflow_run.head_branch }}-${{ vars.WEBSITE_URL }}
      TF_VAR_ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      TF_VAR_CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      TF_VAR_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    name: Deploy preview infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/update-infra
        with:
          BRANCH_NAME: ${{ env.TF_VAR_BRANCH_NAME }}

  deploy-apps:
    needs: deploy-infra
    environment: preview
    name: Deploy apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy-app
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          API_URL: ${{ vars.API_URL }}
