name: 'Deploy preview environment'

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy-infra:
    env:
      WORKSPACE_NAME: ${{ github.head_ref }}
      API_URL: ${{ github.head_ref}}-${{ vars.API_URL }}
      WEBSITE_URL: ${{ github.head_ref}}-${{ vars.WEBSITE_URL }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}

    environment: preview

    name: Deploy preview infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy infra
        uses: ./.github/actions/infra
