name: 'Deploy preview environment'

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - in_progress

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-infra:
    environment: preview

    name: Deploy preview infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/update-infra
        with:
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
          API_URL: ${{ vars.API_URL }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

  deploy-apps:
    needs: deploy-infra
    environment: preview
    name: Deploy apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy-app
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          BRANCH_NAME: ${{ github.event.workflow_run.head_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          API_URL: ${{ vars.API_URL }}
