name: 'Lint dependencies update'

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    tags:
      - 'dependencies'


permissions:
  contents: read

jobs:
  lint-dependencies-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
        shell: bash
      - run: npm run lint
        shell: bash