name: 'Check infra'

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-infra:
    name: Check infra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ls -la

      - name: Run Check Infra Action
        uses: .github/actions/check-infra
        with:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          INFRA_DIR: packages/infra
