name: 'Check infra'

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-infra:
    name: Check infra
    uses: ./.github/actions/check-infra
    with:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      INFRA_DIR: ./packages/infra
