name: 'Release'

on:
  release:
    types: [published]


jobs:
  check-infra:
    name: Check infra
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Check Infra Action
        uses: ./.github/actions/check-infra
        with:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          INFRA_DIR: ./packages/infra/prod

  deploy-infra:
    name: Deploy infra
    runs-on: ubuntu-latest
    needs: check-infra

    steps:
      - uses: actions/checkout@v4

      - name: Run Deploy Infra Action
        uses: ./.github/actions/deploy-infra
        with:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          INFRA_DIR: ./packages/infra/prod

  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: deploy-infra

    steps:
      - uses: actions/checkout@v4

      - name: Run Deploy App Action
        uses: ./.github/actions/deploy-app
        with:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          API_ENV: production
