name: 'Release'

on:
  release:
    types: [published]

jobs:
  check-infra:
    name: Check infra
    uses: ./.github/actions/check-infra
    with:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      INFRA_DIR: ./packages/infra

  deploy-infra:
    name: Deploy infra
    needs: check-infra
    uses: ./.github/actions/deploy-infra
    with:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      INFRA_DIR: ./packages/infra

  deploy-app:
    name: Deploy app
    needs: deploy-infra
    uses: ./.github/actions/deploy-app
    with:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
