name: 'Release'

on:
  release:
    types: [published]

jobs:
  check-infra:
    name: Check infra
    uses: ./.github/actions/check-infra

  deploy-infra:
    name: Deploy infra
    needs: check-infra
    uses: ./.github/actions/deploy-infra

  deploy-app:
    name: Deploy app
    needs: deploy-infra
    uses: ./.github/actions/deploy-app
