name: 'Release'

concurrency: production

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy-production-apps:
    environment: production
    env:
      BRANCH_NAME: 'production'

    name: Deploy production infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env variables
        uses: ./.github/actions/set-env-variables
        with:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          API_URL: ${{ vars.API_URL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy terraform
        uses: ./.github/actions/deploy-terraform
        with:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
