name: 'Update infra'

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  deploy-infra:
    environment: staging

    name: Deploy staging infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy infra
        uses: ./.github/actions/infra
        with:
          WORKSPACE_NAME: ${{ vars.ENVIRONMENT }}
          API_URL: ${{ vars.API_URL }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
