name: 'Update infra'

on:
  push:
    branches: [ "main"]

permissions:
  contents: read

jobs:
  deploy-infra:
    environment: staging

    name: Deploy staging infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy infra
        uses: ./.github/actions/infra
        with:
          WORKSPACE_NAME: ${{ vars.ENVIRONMENT }}
          API_URL: ${{ vars.API_URL }}
          WEBSITE_URL: ${{ vars.WEBSITE_URL }}
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
