name: variables

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/github-script@v7
        with:
          script: |
            console.log(${{ github }})
