name: variables

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.workflow_run.head_branch) }}
        run: |
          echo "$GITHUB_CONTEXT"
